language: r
# cache: packages
sudo: required
repos:
  CRAN: https://cloud.r-project.org
  bcgov: https://bcgov.github.io/drat

#before_install:
#  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
#  - sudo apt-get --yes --force-yes update -qq
#  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      
r_packages: 
  - devtools
  - bcmaps.rdata

matrix:
  include:
    - os: linux
      r: devel

    - os: linux
      r: release

    - os: osx
      r: devel
      
    - os: osx
      r: release

  allow_failures:
    - os: osx
      r: devel

notifications:
  email:
    on_success: change
    on_failure: change
